/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class BatchCreateReferenceProfileUploadResponse {
    /**
     * BatchCreateReferenceProfileUpload default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.BatchLogSessionReferenceResponse batchLogSessionReferenceResponse;

    public BatchCreateReferenceProfileUploadResponse withBatchLogSessionReferenceResponse(ai.whylabs.WhyLabs.models.shared.BatchLogSessionReferenceResponse batchLogSessionReferenceResponse) {
        this.batchLogSessionReferenceResponse = batchLogSessionReferenceResponse;
        return this;
    }
    
    
    public String contentType;

    public BatchCreateReferenceProfileUploadResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public BatchCreateReferenceProfileUploadResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public BatchCreateReferenceProfileUploadResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public BatchCreateReferenceProfileUploadResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
