/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class CreateOrganizationResponse {
    
    public String contentType;

    public CreateOrganizationResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A summary of the organization object if succeeds
     */
    
    public ai.whylabs.WhyLabs.models.shared.OrganizationSummary organizationSummary;

    public CreateOrganizationResponse withOrganizationSummary(ai.whylabs.WhyLabs.models.shared.OrganizationSummary organizationSummary) {
        this.organizationSummary = organizationSummary;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateOrganizationResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateOrganizationResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public CreateOrganizationResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
