/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateReferenceProfileRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ai.whylabs.WhyLabs.models.shared.CreateReferenceProfileRequest createReferenceProfileRequest;

    public CreateReferenceProfileRequest withCreateReferenceProfileRequest(ai.whylabs.WhyLabs.models.shared.CreateReferenceProfileRequest createReferenceProfileRequest) {
        this.createReferenceProfileRequest = createReferenceProfileRequest;
        return this;
    }
    
    /**
     * The unique model ID in your company.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=dataset_id")
    public String datasetId;

    public CreateReferenceProfileRequest withDatasetId(String datasetId) {
        this.datasetId = datasetId;
        return this;
    }
    
    /**
     * Your company's unique organization ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public CreateReferenceProfileRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public CreateReferenceProfileRequest(@JsonProperty("CreateReferenceProfileRequest") ai.whylabs.WhyLabs.models.shared.CreateReferenceProfileRequest createReferenceProfileRequest, @JsonProperty("dataset_id") String datasetId, @JsonProperty("org_id") String orgId) {
        this.createReferenceProfileRequest = createReferenceProfileRequest;
        this.datasetId = datasetId;
        this.orgId = orgId;
  }
}
