/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class CreateReferenceProfileUploadResponse {
    
    public String contentType;

    public CreateReferenceProfileUploadResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * CreateReferenceProfileUpload default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.LogSessionReferenceResponse logSessionReferenceResponse;

    public CreateReferenceProfileUploadResponse withLogSessionReferenceResponse(ai.whylabs.WhyLabs.models.shared.LogSessionReferenceResponse logSessionReferenceResponse) {
        this.logSessionReferenceResponse = logSessionReferenceResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateReferenceProfileUploadResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateReferenceProfileUploadResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public CreateReferenceProfileUploadResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
