/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CreateDatasetProfileUploadResponse {
    /**
     * CreateDatasetProfileUpload default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.AsyncLogResponse asyncLogResponse;

    public CreateDatasetProfileUploadResponse withAsyncLogResponse(ai.whylabs.WhyLabs.models.shared.AsyncLogResponse asyncLogResponse) {
        this.asyncLogResponse = asyncLogResponse;
        return this;
    }
    
    
    public String contentType;

    public CreateDatasetProfileUploadResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateDatasetProfileUploadResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateDatasetProfileUploadResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public CreateDatasetProfileUploadResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
