/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CreateReferenceProfileResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public CreateReferenceProfileResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The metadata for the summarized reference profile data
     */
    
    public ai.whylabs.WhyLabs.models.shared.CreateReferenceProfileResponse createReferenceProfileResponse;

    public CreateReferenceProfileResponse withCreateReferenceProfileResponse(ai.whylabs.WhyLabs.models.shared.CreateReferenceProfileResponse createReferenceProfileResponse) {
        this.createReferenceProfileResponse = createReferenceProfileResponse;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public CreateReferenceProfileResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public CreateReferenceProfileResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public CreateReferenceProfileResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode, @JsonProperty("RawResponse") HttpResponse<byte[]> rawResponse) {
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
  }
}
