/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateOrganizationMembershipRequest {
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=email")
    public String email;

    public CreateOrganizationMembershipRequest withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public CreateOrganizationMembershipRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=role")
    public ai.whylabs.WhyLabs.models.shared.Role role;

    public CreateOrganizationMembershipRequest withRole(ai.whylabs.WhyLabs.models.shared.Role role) {
        this.role = role;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=set_default")
    public Boolean setDefault;

    public CreateOrganizationMembershipRequest withSetDefault(Boolean setDefault) {
        this.setDefault = setDefault;
        return this;
    }
    
    public CreateOrganizationMembershipRequest(@JsonProperty("email") String email, @JsonProperty("org_id") String orgId, @JsonProperty("role") ai.whylabs.WhyLabs.models.shared.Role role) {
        this.email = email;
        this.orgId = orgId;
        this.role = role;
  }
}
