/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class DeactivateModelResponse {
    
    public String contentType;

    public DeactivateModelResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The [ModelMetadataResponse] if operation succeeds
     */
    
    public ai.whylabs.WhyLabs.models.shared.ModelMetadataResponse modelMetadataResponse;

    public DeactivateModelResponse withModelMetadataResponse(ai.whylabs.WhyLabs.models.shared.ModelMetadataResponse modelMetadataResponse) {
        this.modelMetadataResponse = modelMetadataResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public DeactivateModelResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DeactivateModelResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public DeactivateModelResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
