/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class DeleteReferenceProfileResponse {
    
    public String contentType;

    public DeleteReferenceProfileResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * true if successful, false if we encounter failures
     */
    
    public Boolean deleteReferenceProfileDefaultApplicationJSONBoolean;

    public DeleteReferenceProfileResponse withDeleteReferenceProfileDefaultApplicationJSONBoolean(Boolean deleteReferenceProfileDefaultApplicationJSONBoolean) {
        this.deleteReferenceProfileDefaultApplicationJSONBoolean = deleteReferenceProfileDefaultApplicationJSONBoolean;
        return this;
    }
    
    
    public Integer statusCode;

    public DeleteReferenceProfileResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DeleteReferenceProfileResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public DeleteReferenceProfileResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
