/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class DeleteAccountUserRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public DeleteAccountUserRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=user_id")
    public String userId;

    public DeleteAccountUserRequest withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public DeleteAccountUserRequest(@JsonProperty("org_id") String orgId, @JsonProperty("user_id") String userId) {
        this.orgId = orgId;
        this.userId = userId;
  }
}
