/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class DeleteDatasetProfilesResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public DeleteDatasetProfilesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The [DeleteDatasetProfilesResponse] if operation succeeds
     */
    
    public ai.whylabs.WhyLabs.models.shared.DeleteDatasetProfilesResponse deleteDatasetProfilesResponse;

    public DeleteDatasetProfilesResponse withDeleteDatasetProfilesResponse(ai.whylabs.WhyLabs.models.shared.DeleteDatasetProfilesResponse deleteDatasetProfilesResponse) {
        this.deleteDatasetProfilesResponse = deleteDatasetProfilesResponse;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public DeleteDatasetProfilesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public DeleteDatasetProfilesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public DeleteDatasetProfilesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
