/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class DeleteReferenceProfileRequest {
    /**
     * The unique model ID in your company.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=model_id")
    public String modelId;

    public DeleteReferenceProfileRequest withModelId(String modelId) {
        this.modelId = modelId;
        return this;
    }
    
    /**
     * Your company's unique organization ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public DeleteReferenceProfileRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * Unique reference Id.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=reference_id")
    public String referenceId;

    public DeleteReferenceProfileRequest withReferenceId(String referenceId) {
        this.referenceId = referenceId;
        return this;
    }
    
    public DeleteReferenceProfileRequest(@JsonProperty("model_id") String modelId, @JsonProperty("org_id") String orgId, @JsonProperty("reference_id") String referenceId) {
        this.modelId = modelId;
        this.orgId = orgId;
        this.referenceId = referenceId;
  }
}
