/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ExportTracesJsonRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public String[] requestBody;

    public ExportTracesJsonRequest withRequestBody(String[] requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-WHYLABS-RESOURCE")
    public String xWhylabsResource;

    public ExportTracesJsonRequest withXWhylabsResource(String xWhylabsResource) {
        this.xWhylabsResource = xWhylabsResource;
        return this;
    }
    
    public ExportTracesJsonRequest(@JsonProperty("RequestBody") String[] requestBody) {
        this.requestBody = requestBody;
  }
}
