/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class GenerateReportRequest {
    /**
     * A type of admin report.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=report_type")
    public ai.whylabs.WhyLabs.models.shared.AdminReportType reportType;

    public GenerateReportRequest withReportType(ai.whylabs.WhyLabs.models.shared.AdminReportType reportType) {
        this.reportType = reportType;
        return this;
    }
    
    public GenerateReportRequest(@JsonProperty("report_type") ai.whylabs.WhyLabs.models.shared.AdminReportType reportType) {
        this.reportType = reportType;
  }
}
