/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetAccountUsersResponse {
    
    public String contentType;

    public GetAccountUsersResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * GetAccountUsers default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.GetAccountUsersResponse getAccountUsersResponse;

    public GetAccountUsersResponse withGetAccountUsersResponse(ai.whylabs.WhyLabs.models.shared.GetAccountUsersResponse getAccountUsersResponse) {
        this.getAccountUsersResponse = getAccountUsersResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public GetAccountUsersResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetAccountUsersResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetAccountUsersResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
