/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetAWSMarketplaceMetadataResponse {
    
    public String contentType;

    public GetAWSMarketplaceMetadataResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * GetAWSMarketplaceMetadata default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.GetMarketplaceMetadataResponse getMarketplaceMetadataResponse;

    public GetAWSMarketplaceMetadataResponse withGetMarketplaceMetadataResponse(ai.whylabs.WhyLabs.models.shared.GetMarketplaceMetadataResponse getMarketplaceMetadataResponse) {
        this.getMarketplaceMetadataResponse = getMarketplaceMetadataResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public GetAWSMarketplaceMetadataResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetAWSMarketplaceMetadataResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetAWSMarketplaceMetadataResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
