/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetAccountMembershipsResponse {
    
    public String contentType;

    public GetAccountMembershipsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * GetAccountMemberships default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.GetAccountMembershipsResponse getAccountMembershipsResponse;

    public GetAccountMembershipsResponse withGetAccountMembershipsResponse(ai.whylabs.WhyLabs.models.shared.GetAccountMembershipsResponse getAccountMembershipsResponse) {
        this.getAccountMembershipsResponse = getAccountMembershipsResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public GetAccountMembershipsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetAccountMembershipsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetAccountMembershipsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
