/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetColumnWeightsResponse {
    
    public String contentType;

    public GetColumnWeightsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * GetColumnWeights default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.EntityWeightRecord entityWeightRecord;

    public GetColumnWeightsResponse withEntityWeightRecord(ai.whylabs.WhyLabs.models.shared.EntityWeightRecord entityWeightRecord) {
        this.entityWeightRecord = entityWeightRecord;
        return this;
    }
    
    
    public Integer statusCode;

    public GetColumnWeightsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetColumnWeightsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetColumnWeightsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
