/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetEntitySchemaResponse {
    
    public String contentType;

    public GetEntitySchemaResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * GetEntitySchema default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.EntitySchema entitySchema;

    public GetEntitySchemaResponse withEntitySchema(ai.whylabs.WhyLabs.models.shared.EntitySchema entitySchema) {
        this.entitySchema = entitySchema;
        return this;
    }
    
    
    public Integer statusCode;

    public GetEntitySchemaResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetEntitySchemaResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetEntitySchemaResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
