/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class GetFeatureFlagsRequest {
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=org_id")
    public String orgId;

    public GetFeatureFlagsRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=user_id")
    public String userId;

    public GetFeatureFlagsRequest withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public GetFeatureFlagsRequest(@JsonProperty("org_id") String orgId, @JsonProperty("user_id") String userId) {
        this.orgId = orgId;
        this.userId = userId;
  }
}
