/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GetMonitorConfigV3Request {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=dataset_id")
    public String datasetId;

    public GetMonitorConfigV3Request withDatasetId(String datasetId) {
        this.datasetId = datasetId;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=include_entity_schema")
    public Boolean includeEntitySchema;

    public GetMonitorConfigV3Request withIncludeEntitySchema(Boolean includeEntitySchema) {
        this.includeEntitySchema = includeEntitySchema;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=include_entity_weights")
    public Boolean includeEntityWeights;

    public GetMonitorConfigV3Request withIncludeEntityWeights(Boolean includeEntityWeights) {
        this.includeEntityWeights = includeEntityWeights;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public GetMonitorConfigV3Request withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public GetMonitorConfigV3Request(@JsonProperty("dataset_id") String datasetId, @JsonProperty("org_id") String orgId) {
        this.datasetId = datasetId;
        this.orgId = orgId;
  }
}
