/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetMonitorResponse {
    
    public String contentType;

    public GetMonitorResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * GetMonitor default response
     */
    
    public String getMonitorDefaultApplicationJSONString;

    public GetMonitorResponse withGetMonitorDefaultApplicationJSONString(String getMonitorDefaultApplicationJSONString) {
        this.getMonitorDefaultApplicationJSONString = getMonitorDefaultApplicationJSONString;
        return this;
    }
    
    
    public Integer statusCode;

    public GetMonitorResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetMonitorResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetMonitorResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
