/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class GetMembershipsByEmailRequest {
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=email")
    public String email;

    public GetMembershipsByEmailRequest withEmail(String email) {
        this.email = email;
        return this;
    }
    
    public GetMembershipsByEmailRequest(@JsonProperty("email") String email) {
        this.email = email;
  }
}
