/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetMonitorConfigSchemaResponse {
    
    public String contentType;

    public GetMonitorConfigSchemaResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * GetMonitorConfigSchema default response
     */
    
    public String getMonitorConfigSchemaDefaultApplicationJSONString;

    public GetMonitorConfigSchemaResponse withGetMonitorConfigSchemaDefaultApplicationJSONString(String getMonitorConfigSchemaDefaultApplicationJSONString) {
        this.getMonitorConfigSchemaDefaultApplicationJSONString = getMonitorConfigSchemaDefaultApplicationJSONString;
        return this;
    }
    
    
    public Integer statusCode;

    public GetMonitorConfigSchemaResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetMonitorConfigSchemaResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetMonitorConfigSchemaResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
