/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class GetMonitorConfigV3VersionRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=dataset_id")
    public String datasetId;

    public GetMonitorConfigV3VersionRequest withDatasetId(String datasetId) {
        this.datasetId = datasetId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public GetMonitorConfigV3VersionRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=version_id")
    public String versionId;

    public GetMonitorConfigV3VersionRequest withVersionId(String versionId) {
        this.versionId = versionId;
        return this;
    }
    
    public GetMonitorConfigV3VersionRequest(@JsonProperty("dataset_id") String datasetId, @JsonProperty("org_id") String orgId, @JsonProperty("version_id") String versionId) {
        this.datasetId = datasetId;
        this.orgId = orgId;
        this.versionId = versionId;
  }
}
