/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetNotificationActionResponse {
    
    public String contentType;

    public GetNotificationActionResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * GetNotificationAction default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.NotificationAction notificationAction;

    public GetNotificationActionResponse withNotificationAction(ai.whylabs.WhyLabs.models.shared.NotificationAction notificationAction) {
        this.notificationAction = notificationAction;
        return this;
    }
    
    
    public Integer statusCode;

    public GetNotificationActionResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetNotificationActionResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetNotificationActionResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
