/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class GetNotificationActionRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=action_id")
    public String actionId;

    public GetNotificationActionRequest withActionId(String actionId) {
        this.actionId = actionId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public GetNotificationActionRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public GetNotificationActionRequest(@JsonProperty("action_id") String actionId, @JsonProperty("org_id") String orgId) {
        this.actionId = actionId;
        this.orgId = orgId;
  }
}
