/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class GetOrgRoleMembershipsRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=managed_org_id")
    public String managedOrgId;

    public GetOrgRoleMembershipsRequest withManagedOrgId(String managedOrgId) {
        this.managedOrgId = managedOrgId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public GetOrgRoleMembershipsRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=role")
    public String role;

    public GetOrgRoleMembershipsRequest withRole(String role) {
        this.role = role;
        return this;
    }
    
    public GetOrgRoleMembershipsRequest(@JsonProperty("managed_org_id") String managedOrgId, @JsonProperty("org_id") String orgId, @JsonProperty("role") String role) {
        this.managedOrgId = managedOrgId;
        this.orgId = orgId;
        this.role = role;
  }
}
