/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetOrgRoleMembershipsResponse {
    
    public String contentType;

    public GetOrgRoleMembershipsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * GetOrgRoleMemberships default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.GetAccountMembershipsResponse getAccountMembershipsResponse;

    public GetOrgRoleMembershipsResponse withGetAccountMembershipsResponse(ai.whylabs.WhyLabs.models.shared.GetAccountMembershipsResponse getAccountMembershipsResponse) {
        this.getAccountMembershipsResponse = getAccountMembershipsResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public GetOrgRoleMembershipsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetOrgRoleMembershipsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetOrgRoleMembershipsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
