/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetPagerDutyNotificationActionPayloadResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public GetPagerDutyNotificationActionPayloadResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * getPagerDutyNotificationActionPayload default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.PagerDutyNotificationAction pagerDutyNotificationAction;

    public GetPagerDutyNotificationActionPayloadResponse withPagerDutyNotificationAction(ai.whylabs.WhyLabs.models.shared.PagerDutyNotificationAction pagerDutyNotificationAction) {
        this.pagerDutyNotificationAction = pagerDutyNotificationAction;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public GetPagerDutyNotificationActionPayloadResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public GetPagerDutyNotificationActionPayloadResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetPagerDutyNotificationActionPayloadResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode, @JsonProperty("RawResponse") HttpResponse<byte[]> rawResponse) {
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
  }
}
