/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class GetProfileObservatoryLinkRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ai.whylabs.WhyLabs.models.shared.GetProfileObservatoryLinkRequest getProfileObservatoryLinkRequest;

    public GetProfileObservatoryLinkRequest withGetProfileObservatoryLinkRequest(ai.whylabs.WhyLabs.models.shared.GetProfileObservatoryLinkRequest getProfileObservatoryLinkRequest) {
        this.getProfileObservatoryLinkRequest = getProfileObservatoryLinkRequest;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=dataset_id")
    public String datasetId;

    public GetProfileObservatoryLinkRequest withDatasetId(String datasetId) {
        this.datasetId = datasetId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public GetProfileObservatoryLinkRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public GetProfileObservatoryLinkRequest(@JsonProperty("GetProfileObservatoryLinkRequest") ai.whylabs.WhyLabs.models.shared.GetProfileObservatoryLinkRequest getProfileObservatoryLinkRequest, @JsonProperty("dataset_id") String datasetId, @JsonProperty("org_id") String orgId) {
        this.getProfileObservatoryLinkRequest = getProfileObservatoryLinkRequest;
        this.datasetId = datasetId;
        this.orgId = orgId;
  }
}
