/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetProfileTracesResponse {
    
    public String contentType;

    public GetProfileTracesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * GetProfileTraces default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.ProfileTracesResponse profileTracesResponse;

    public GetProfileTracesResponse withProfileTracesResponse(ai.whylabs.WhyLabs.models.shared.ProfileTracesResponse profileTracesResponse) {
        this.profileTracesResponse = profileTracesResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public GetProfileTracesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetProfileTracesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetProfileTracesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
