/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetReferenceProfileResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public GetReferenceProfileResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The metadata for the summarized dataset profile including paths to JSON and protobuf data
     */
    
    public ai.whylabs.WhyLabs.models.shared.ReferenceProfileItemResponse referenceProfileItemResponse;

    public GetReferenceProfileResponse withReferenceProfileItemResponse(ai.whylabs.WhyLabs.models.shared.ReferenceProfileItemResponse referenceProfileItemResponse) {
        this.referenceProfileItemResponse = referenceProfileItemResponse;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public GetReferenceProfileResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public GetReferenceProfileResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetReferenceProfileResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
