/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetSessionProfileObservatoryLinkResponse {
    
    public String contentType;

    public GetSessionProfileObservatoryLinkResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * GetSessionProfileObservatoryLink default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.GetProfileObservatoryLinkResponse getProfileObservatoryLinkResponse;

    public GetSessionProfileObservatoryLinkResponse withGetProfileObservatoryLinkResponse(ai.whylabs.WhyLabs.models.shared.GetProfileObservatoryLinkResponse getProfileObservatoryLinkResponse) {
        this.getProfileObservatoryLinkResponse = getProfileObservatoryLinkResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public GetSessionProfileObservatoryLinkResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetSessionProfileObservatoryLinkResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetSessionProfileObservatoryLinkResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
