/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetSlackNotificationActionPayloadResponse {
    
    public String contentType;

    public GetSlackNotificationActionPayloadResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * getSlackNotificationActionPayload default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.SlackNotificationAction slackNotificationAction;

    public GetSlackNotificationActionPayloadResponse withSlackNotificationAction(ai.whylabs.WhyLabs.models.shared.SlackNotificationAction slackNotificationAction) {
        this.slackNotificationAction = slackNotificationAction;
        return this;
    }
    
    
    public Integer statusCode;

    public GetSlackNotificationActionPayloadResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetSlackNotificationActionPayloadResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetSlackNotificationActionPayloadResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
