/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class GetSessionProfileObservatoryLinkRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ai.whylabs.WhyLabs.models.shared.GetProfileObservatoryLinkRequest getProfileObservatoryLinkRequest;

    public GetSessionProfileObservatoryLinkRequest withGetProfileObservatoryLinkRequest(ai.whylabs.WhyLabs.models.shared.GetProfileObservatoryLinkRequest getProfileObservatoryLinkRequest) {
        this.getProfileObservatoryLinkRequest = getProfileObservatoryLinkRequest;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=session_id")
    public String sessionId;

    public GetSessionProfileObservatoryLinkRequest withSessionId(String sessionId) {
        this.sessionId = sessionId;
        return this;
    }
    
    public GetSessionProfileObservatoryLinkRequest(@JsonProperty("GetProfileObservatoryLinkRequest") ai.whylabs.WhyLabs.models.shared.GetProfileObservatoryLinkRequest getProfileObservatoryLinkRequest, @JsonProperty("session_id") String sessionId) {
        this.getProfileObservatoryLinkRequest = getProfileObservatoryLinkRequest;
        this.sessionId = sessionId;
  }
}
