/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class HideSegmentsRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ai.whylabs.WhyLabs.models.shared.SegmentsListRequest segmentsListRequest;

    public HideSegmentsRequest withSegmentsListRequest(ai.whylabs.WhyLabs.models.shared.SegmentsListRequest segmentsListRequest) {
        this.segmentsListRequest = segmentsListRequest;
        return this;
    }
    
    /**
     * The unique dataset ID in your company.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=dataset_id")
    public String datasetId;

    public HideSegmentsRequest withDatasetId(String datasetId) {
        this.datasetId = datasetId;
        return this;
    }
    
    /**
     * Your company's unique organization ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public HideSegmentsRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public HideSegmentsRequest(@JsonProperty("SegmentsListRequest") ai.whylabs.WhyLabs.models.shared.SegmentsListRequest segmentsListRequest, @JsonProperty("dataset_id") String datasetId, @JsonProperty("org_id") String orgId) {
        this.segmentsListRequest = segmentsListRequest;
        this.datasetId = datasetId;
        this.orgId = orgId;
  }
}
