/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListDeleteDatasetProfilesRequestsResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public ListDeleteDatasetProfilesRequestsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public ListDeleteDatasetProfilesRequestsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public ListDeleteDatasetProfilesRequestsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The list of [DeleteProfile] requests if operation succeeds
     */
    
    public ai.whylabs.WhyLabs.models.shared.DeleteProfile[] classes;

    public ListDeleteDatasetProfilesRequestsResponse withClasses(ai.whylabs.WhyLabs.models.shared.DeleteProfile[] classes) {
        this.classes = classes;
        return this;
    }
    
    public ListDeleteDatasetProfilesRequestsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode, @JsonProperty("RawResponse") HttpResponse<byte[]> rawResponse) {
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
  }
}
