/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ListApiKeysRequest {
    /**
     * Your company's unique organization ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public ListApiKeysRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * The unique user ID in an organization.
     *  A list of objects with key ID and other metadata about the keys, but no secret values
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=user_id")
    public String userId;

    public ListApiKeysRequest withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public ListApiKeysRequest(@JsonProperty("org_id") String orgId) {
        this.orgId = orgId;
  }
}
