/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ListSegmentsRequest {
    /**
     * The unique model ID in your company.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=model_id")
    public String modelId;

    public ListSegmentsRequest withModelId(String modelId) {
        this.modelId = modelId;
        return this;
    }
    
    /**
     * Your company's unique organization ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public ListSegmentsRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public ListSegmentsRequest(@JsonProperty("model_id") String modelId, @JsonProperty("org_id") String orgId) {
        this.modelId = modelId;
        this.orgId = orgId;
  }
}
