/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListApiKeysResponse {
    
    public String contentType;

    public ListApiKeysResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A list of objects with key ID and other metadata about the keys, but no secret values
     */
    
    public ai.whylabs.WhyLabs.models.shared.ListUserApiKeys listUserApiKeys;

    public ListApiKeysResponse withListUserApiKeys(ai.whylabs.WhyLabs.models.shared.ListUserApiKeys listUserApiKeys) {
        this.listUserApiKeys = listUserApiKeys;
        return this;
    }
    
    
    public Integer statusCode;

    public ListApiKeysResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListApiKeysResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ListApiKeysResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
