/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListReferenceProfilesResponse {
    
    public String contentType;

    public ListReferenceProfilesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The metadata for the summarized dataset profile including paths to JSON and protobuf data
     */
    
    public ai.whylabs.WhyLabs.models.shared.ReferenceProfileItemResponse[] referenceProfileItemResponses;

    public ListReferenceProfilesResponse withReferenceProfileItemResponses(ai.whylabs.WhyLabs.models.shared.ReferenceProfileItemResponse[] referenceProfileItemResponses) {
        this.referenceProfileItemResponses = referenceProfileItemResponses;
        return this;
    }
    
    
    public Integer statusCode;

    public ListReferenceProfilesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListReferenceProfilesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ListReferenceProfilesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
