/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListManagedOrganizationsResponse {
    /**
     * ListManagedOrganizations default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.AccountOrganization[] accountOrganizations;

    public ListManagedOrganizationsResponse withAccountOrganizations(ai.whylabs.WhyLabs.models.shared.AccountOrganization[] accountOrganizations) {
        this.accountOrganizations = accountOrganizations;
        return this;
    }
    
    
    public String contentType;

    public ListManagedOrganizationsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public ListManagedOrganizationsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListManagedOrganizationsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ListManagedOrganizationsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
