/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ListProfileTracesRequest {
    /**
     * The unique dataset ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=dataset_id")
    public String datasetId;

    public ListProfileTracesRequest withDatasetId(String datasetId) {
        this.datasetId = datasetId;
        return this;
    }
    
    /**
     * Milli epoch time that represents the end of the time range to query.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=from_epoch")
    public Long fromEpoch;

    public ListProfileTracesRequest withFromEpoch(Long fromEpoch) {
        this.fromEpoch = fromEpoch;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    public Integer limit;

    public ListProfileTracesRequest withLimit(Integer limit) {
        this.limit = limit;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=offset")
    public Integer offset;

    public ListProfileTracesRequest withOffset(Integer offset) {
        this.offset = offset;
        return this;
    }
    
    /**
     * Your company's unique organization ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public ListProfileTracesRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * Milli epoch time that represents the end of the time range to query.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=to_epoch")
    public Long toEpoch;

    public ListProfileTracesRequest withToEpoch(Long toEpoch) {
        this.toEpoch = toEpoch;
        return this;
    }
    
    public ListProfileTracesRequest(@JsonProperty("dataset_id") String datasetId, @JsonProperty("from_epoch") Long fromEpoch, @JsonProperty("org_id") String orgId, @JsonProperty("to_epoch") Long toEpoch) {
        this.datasetId = datasetId;
        this.fromEpoch = fromEpoch;
        this.orgId = orgId;
        this.toEpoch = toEpoch;
  }
}
