/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ListModelsRequest {
    /**
     * Your company's unique organization ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public ListModelsRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public ListModelsRequest(@JsonProperty("org_id") String orgId) {
        this.orgId = orgId;
  }
}
