/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class LogDebugEventResponse {
    
    public String contentType;

    public LogDebugEventResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * 202 if the response is accepted
     */
    
    public String logDebugEventDefaultApplicationJSONString;

    public LogDebugEventResponse withLogDebugEventDefaultApplicationJSONString(String logDebugEventDefaultApplicationJSONString) {
        this.logDebugEventDefaultApplicationJSONString = logDebugEventDefaultApplicationJSONString;
        return this;
    }
    
    
    public Integer statusCode;

    public LogDebugEventResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public LogDebugEventResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public LogDebugEventResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
