/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PartiallyUpdateOrgRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PartiallyUpdateOrgRequestBody requestBody;

    public PartiallyUpdateOrgRequest withRequestBody(PartiallyUpdateOrgRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Domain associated with this organization
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=domain")
    public String domain;

    public PartiallyUpdateOrgRequest withDomain(String domain) {
        this.domain = domain;
        return this;
    }
    
    /**
     * The name of the organization
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=name")
    public String name;

    public PartiallyUpdateOrgRequest withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Email address that should be used for notifications for this organization
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=notification_email_address")
    public String notificationEmailAddress;

    public PartiallyUpdateOrgRequest withNotificationEmailAddress(String notificationEmailAddress) {
        this.notificationEmailAddress = notificationEmailAddress;
        return this;
    }
    
    /**
     * Url that users of this organization will be redirected to in some cases (such as via Siren notifications). NOTE: should NOT be followed by a trailing slash!
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=observatory_url")
    public String observatoryUrl;

    public PartiallyUpdateOrgRequest withObservatoryUrl(String observatoryUrl) {
        this.observatoryUrl = observatoryUrl;
        return this;
    }
    
    /**
     * Slack Webhook that should be used for notifications for this organization
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=slack_webhook")
    public String slackWebhook;

    public PartiallyUpdateOrgRequest withSlackWebhook(String slackWebhook) {
        this.slackWebhook = slackWebhook;
        return this;
    }
    
    /**
     * Organization's subscription tier. Should be PAID for real customers
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=subscription_tier")
    public ai.whylabs.WhyLabs.models.shared.SubscriptionTier subscriptionTier;

    public PartiallyUpdateOrgRequest withSubscriptionTier(ai.whylabs.WhyLabs.models.shared.SubscriptionTier subscriptionTier) {
        this.subscriptionTier = subscriptionTier;
        return this;
    }
    
    public PartiallyUpdateOrgRequest(@JsonProperty("RequestBody") PartiallyUpdateOrgRequestBody requestBody) {
        this.requestBody = requestBody;
  }
}
