/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class PartiallyUpdateOrganizationResponse {
    
    public String contentType;

    public PartiallyUpdateOrganizationResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A summary of the organization object if succeeds
     */
    
    public ai.whylabs.WhyLabs.models.shared.OrganizationSummary organizationSummary;

    public PartiallyUpdateOrganizationResponse withOrganizationSummary(ai.whylabs.WhyLabs.models.shared.OrganizationSummary organizationSummary) {
        this.organizationSummary = organizationSummary;
        return this;
    }
    
    
    public Integer statusCode;

    public PartiallyUpdateOrganizationResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PartiallyUpdateOrganizationResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PartiallyUpdateOrganizationResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
