/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class PatchMonitorConfigV3Response {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public PatchMonitorConfigV3Response withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * PatchMonitorConfigV3 default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.Response response;

    public PatchMonitorConfigV3Response withResponse(ai.whylabs.WhyLabs.models.shared.Response response) {
        this.response = response;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public PatchMonitorConfigV3Response withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public PatchMonitorConfigV3Response withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PatchMonitorConfigV3Response(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
