/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class PatchOrganizationMembershipsResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public PatchOrganizationMembershipsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public PatchOrganizationMembershipsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public PatchOrganizationMembershipsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * PatchOrganizationMemberships default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.StatusResponse statusResponse;

    public PatchOrganizationMembershipsResponse withStatusResponse(ai.whylabs.WhyLabs.models.shared.StatusResponse statusResponse) {
        this.statusResponse = statusResponse;
        return this;
    }
    
    public PatchOrganizationMembershipsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
