/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class PatchOrgRoleMembershipsRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PatchOrgRoleMembershipsRequestBody requestBody;

    public PatchOrgRoleMembershipsRequest withRequestBody(PatchOrgRoleMembershipsRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=managed_org_id")
    public String managedOrgId;

    public PatchOrgRoleMembershipsRequest withManagedOrgId(String managedOrgId) {
        this.managedOrgId = managedOrgId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public PatchOrgRoleMembershipsRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=role")
    public String role;

    public PatchOrgRoleMembershipsRequest withRole(String role) {
        this.role = role;
        return this;
    }
    
    public PatchOrgRoleMembershipsRequest(@JsonProperty("RequestBody") PatchOrgRoleMembershipsRequestBody requestBody, @JsonProperty("managed_org_id") String managedOrgId, @JsonProperty("org_id") String orgId, @JsonProperty("role") String role) {
        this.requestBody = requestBody;
        this.managedOrgId = managedOrgId;
        this.orgId = orgId;
        this.role = role;
  }
}
