/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class PatchOrgRoleMembershipsRequestBody {
    /**
     * Request for the PatchOrgRoleMemberships API
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("request")
    public ai.whylabs.WhyLabs.models.shared.PatchAccountMembershipsRequest request;

    public PatchOrgRoleMembershipsRequestBody withRequest(ai.whylabs.WhyLabs.models.shared.PatchAccountMembershipsRequest request) {
        this.request = request;
        return this;
    }
    
    public PatchOrgRoleMembershipsRequestBody(){}
}
