/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class PostSpansRawRequest {
    @SpeakeasyMetadata("request:mediaType=application/x-protobuf")
    public byte[] requestBody;

    public PostSpansRawRequest withRequestBody(byte[] requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-WHYLABS-RESOURCE")
    public String xWhylabsResource;

    public PostSpansRawRequest withXWhylabsResource(String xWhylabsResource) {
        this.xWhylabsResource = xWhylabsResource;
        return this;
    }
    
    public PostSpansRawRequest(@JsonProperty("RequestBody") byte[] requestBody, @JsonProperty("X-WHYLABS-RESOURCE") String xWhylabsResource) {
        this.requestBody = requestBody;
        this.xWhylabsResource = xWhylabsResource;
  }
}
