/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ProvisionDatabricksConnectionResponse {
    
    public String contentType;

    public ProvisionDatabricksConnectionResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * ProvisionDatabricksConnection default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.ProvisionDatabricksConnectionResponse provisionDatabricksConnectionResponse;

    public ProvisionDatabricksConnectionResponse withProvisionDatabricksConnectionResponse(ai.whylabs.WhyLabs.models.shared.ProvisionDatabricksConnectionResponse provisionDatabricksConnectionResponse) {
        this.provisionDatabricksConnectionResponse = provisionDatabricksConnectionResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public ProvisionDatabricksConnectionResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ProvisionDatabricksConnectionResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ProvisionDatabricksConnectionResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
