/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ProvisionNewUserResponse {
    
    public String contentType;

    public ProvisionNewUserResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * ProvisionNewUser default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.ProvisionNewUserResponse provisionNewUserResponse;

    public ProvisionNewUserResponse withProvisionNewUserResponse(ai.whylabs.WhyLabs.models.shared.ProvisionNewUserResponse provisionNewUserResponse) {
        this.provisionNewUserResponse = provisionNewUserResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public ProvisionNewUserResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ProvisionNewUserResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ProvisionNewUserResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
