/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class PutEntitySchemaColumnResponse {
    
    public String contentType;

    public PutEntitySchemaColumnResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * PutEntitySchemaColumn default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.Response response;

    public PutEntitySchemaColumnResponse withResponse(ai.whylabs.WhyLabs.models.shared.Response response) {
        this.response = response;
        return this;
    }
    
    
    public Integer statusCode;

    public PutEntitySchemaColumnResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PutEntitySchemaColumnResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PutEntitySchemaColumnResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
