/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PutRequestMonitorRunConfigResponse {
    
    public String contentType;

    public PutRequestMonitorRunConfigResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * PutRequestMonitorRunConfig default response
     */
    
    public String putRequestMonitorRunConfigDefaultApplicationJSONString;

    public PutRequestMonitorRunConfigResponse withPutRequestMonitorRunConfigDefaultApplicationJSONString(String putRequestMonitorRunConfigDefaultApplicationJSONString) {
        this.putRequestMonitorRunConfigDefaultApplicationJSONString = putRequestMonitorRunConfigDefaultApplicationJSONString;
        return this;
    }
    
    
    public Integer statusCode;

    public PutRequestMonitorRunConfigResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PutRequestMonitorRunConfigResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PutRequestMonitorRunConfigResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
