/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class RefreshConnectionResponse {
    
    public String contentType;

    public RefreshConnectionResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * RefreshConnection default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.RefreshConnectionByOrgIdResponse refreshConnectionByOrgIdResponse;

    public RefreshConnectionResponse withRefreshConnectionByOrgIdResponse(ai.whylabs.WhyLabs.models.shared.RefreshConnectionByOrgIdResponse refreshConnectionByOrgIdResponse) {
        this.refreshConnectionByOrgIdResponse = refreshConnectionByOrgIdResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public RefreshConnectionResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public RefreshConnectionResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public RefreshConnectionResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
