/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class RegisterDatabricksConnectionResponse {
    
    public String contentType;

    public RegisterDatabricksConnectionResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * RegisterDatabricksConnection default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.RegisterDatabricksConnectionResponse registerDatabricksConnectionResponse;

    public RegisterDatabricksConnectionResponse withRegisterDatabricksConnectionResponse(ai.whylabs.WhyLabs.models.shared.RegisterDatabricksConnectionResponse registerDatabricksConnectionResponse) {
        this.registerDatabricksConnectionResponse = registerDatabricksConnectionResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public RegisterDatabricksConnectionResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public RegisterDatabricksConnectionResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public RegisterDatabricksConnectionResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
