/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class RevokeApiKeyResponse {
    
    public String contentType;

    public RevokeApiKeyResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public RevokeApiKeyResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public RevokeApiKeyResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Revoked API Key's metadata
     */
    
    public ai.whylabs.WhyLabs.models.shared.UserApiKey userApiKey;

    public RevokeApiKeyResponse withUserApiKey(ai.whylabs.WhyLabs.models.shared.UserApiKey userApiKey) {
        this.userApiKey = userApiKey;
        return this;
    }
    
    public RevokeApiKeyResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
