/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class RevokeApiKeyRequest {
    /**
     * ID of the key to revoke
     *  Metadata for the revoked API Key
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=key_id")
    public String keyId;

    public RevokeApiKeyRequest withKeyId(String keyId) {
        this.keyId = keyId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public RevokeApiKeyRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=user_id")
    public String userId;

    public RevokeApiKeyRequest withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public RevokeApiKeyRequest(@JsonProperty("key_id") String keyId, @JsonProperty("org_id") String orgId, @JsonProperty("user_id") String userId) {
        this.keyId = keyId;
        this.orgId = orgId;
        this.userId = userId;
  }
}
