/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class TransactionStatusRequest {
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=transaction_id")
    public String transactionId;

    public TransactionStatusRequest withTransactionId(String transactionId) {
        this.transactionId = transactionId;
        return this;
    }
    
    public TransactionStatusRequest(@JsonProperty("transaction_id") String transactionId) {
        this.transactionId = transactionId;
  }
}
