/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class UpdateOrganizationMembershipResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public UpdateOrganizationMembershipResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * UpdateOrganizationMembership default response
     */
    
    public ai.whylabs.WhyLabs.models.shared.MembershipMetadata membershipMetadata;

    public UpdateOrganizationMembershipResponse withMembershipMetadata(ai.whylabs.WhyLabs.models.shared.MembershipMetadata membershipMetadata) {
        this.membershipMetadata = membershipMetadata;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public UpdateOrganizationMembershipResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public UpdateOrganizationMembershipResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public UpdateOrganizationMembershipResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode, @JsonProperty("RawResponse") HttpResponse<byte[]> rawResponse) {
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
  }
}
