/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class UpdateOrganizationRequest {
    /**
     * Domain associated with this organization
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=domain")
    public String domain;

    public UpdateOrganizationRequest withDomain(String domain) {
        this.domain = domain;
        return this;
    }
    
    /**
     * Email domains associated with this organization, as a comma separated list
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=email_domains")
    public String emailDomains;

    public UpdateOrganizationRequest withEmailDomains(String emailDomains) {
        this.emailDomains = emailDomains;
        return this;
    }
    
    /**
     * The name of the organization
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=name")
    public String name;

    public UpdateOrganizationRequest withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Email address that should be used for notifications for this organization
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=notification_email_address")
    public String notificationEmailAddress;

    public UpdateOrganizationRequest withNotificationEmailAddress(String notificationEmailAddress) {
        this.notificationEmailAddress = notificationEmailAddress;
        return this;
    }
    
    /**
     * Url that users of this organization will be redirected to in some cases (such as via Siren notifications). NOTE: should NOT be followed by a trailing slash!
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=observatory_url")
    public String observatoryUrl;

    public UpdateOrganizationRequest withObservatoryUrl(String observatoryUrl) {
        this.observatoryUrl = observatoryUrl;
        return this;
    }
    
    /**
     * The unique ID of an organization. If an organization with this ID does not exist, this method will throw an exception.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public UpdateOrganizationRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=pager_duty_key")
    public String pagerDutyKey;

    public UpdateOrganizationRequest withPagerDutyKey(String pagerDutyKey) {
        this.pagerDutyKey = pagerDutyKey;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=parent_org_id")
    public String parentOrgId;

    public UpdateOrganizationRequest withParentOrgId(String parentOrgId) {
        this.parentOrgId = parentOrgId;
        return this;
    }
    
    /**
     * Slack Webhook that should be used for notifications for this organization
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=slack_webhook")
    public String slackWebhook;

    public UpdateOrganizationRequest withSlackWebhook(String slackWebhook) {
        this.slackWebhook = slackWebhook;
        return this;
    }
    
    /**
     * Organization's subscription tier. Should be PAID for real customers
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=subscription_tier")
    public ai.whylabs.WhyLabs.models.shared.SubscriptionTier subscriptionTier;

    public UpdateOrganizationRequest withSubscriptionTier(ai.whylabs.WhyLabs.models.shared.SubscriptionTier subscriptionTier) {
        this.subscriptionTier = subscriptionTier;
        return this;
    }
    
    public UpdateOrganizationRequest(@JsonProperty("name") String name, @JsonProperty("org_id") String orgId) {
        this.name = name;
        this.orgId = orgId;
  }
}
