/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class UpdateAccountUserRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public ai.whylabs.WhyLabs.models.shared.AccountUserRequest accountUserRequest;

    public UpdateAccountUserRequest withAccountUserRequest(ai.whylabs.WhyLabs.models.shared.AccountUserRequest accountUserRequest) {
        this.accountUserRequest = accountUserRequest;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public UpdateAccountUserRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=user_id")
    public String userId;

    public UpdateAccountUserRequest withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public UpdateAccountUserRequest(@JsonProperty("AccountUserRequest") ai.whylabs.WhyLabs.models.shared.AccountUserRequest accountUserRequest, @JsonProperty("org_id") String orgId, @JsonProperty("user_id") String userId) {
        this.accountUserRequest = accountUserRequest;
        this.orgId = orgId;
        this.userId = userId;
  }
}
