/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.operations;

import ai.whylabs.WhyLabs.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ValidateMonitorConfigV3Request {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public String requestBody;

    public ValidateMonitorConfigV3Request withRequestBody(String requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=dataset_id")
    public String datasetId;

    public ValidateMonitorConfigV3Request withDatasetId(String datasetId) {
        this.datasetId = datasetId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org_id")
    public String orgId;

    public ValidateMonitorConfigV3Request withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=verbose")
    public Boolean verbose;

    public ValidateMonitorConfigV3Request withVerbose(Boolean verbose) {
        this.verbose = verbose;
        return this;
    }
    
    public ValidateMonitorConfigV3Request(@JsonProperty("RequestBody") String requestBody, @JsonProperty("dataset_id") String datasetId, @JsonProperty("org_id") String orgId) {
        this.requestBody = requestBody;
        this.datasetId = datasetId;
        this.orgId = orgId;
  }
}
