/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AccountUser - Account User metadata
 */

public class AccountUser {
    /**
     * Flag to indicate if the user is active
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("active")
    public Boolean active;

    public AccountUser withActive(Boolean active) {
        this.active = active;
        return this;
    }
    
    /**
     * The user's email address
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    public String email;

    public AccountUser withEmail(String email) {
        this.email = email;
        return this;
    }
    
    /**
     * External user id
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("externalId")
    public String externalId;

    public AccountUser withExternalId(String externalId) {
        this.externalId = externalId;
        return this;
    }
    
    /**
     * The WhyLabs organization id
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("orgId")
    public String orgId;

    public AccountUser withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * The WhyLabs user id
     */
    @JsonProperty("userId")
    public String userId;

    public AccountUser withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    /**
     * User schema
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("userSchema")
    public String userSchema;

    public AccountUser withUserSchema(String userSchema) {
        this.userSchema = userSchema;
        return this;
    }
    
    public AccountUser(@JsonProperty("userId") String userId) {
        this.userId = userId;
  }
}
