/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AccountOrganization - Response for the GetAccountMemberships API
 */

public class AccountOrganization {
    /**
     * Organization name
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public AccountOrganization withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Organization ID
     */
    @JsonProperty("orgId")
    public String orgId;

    public AccountOrganization withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public AccountOrganization(@JsonProperty("orgId") String orgId) {
        this.orgId = orgId;
  }
}
