/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ActionType {
    EMAIL("EMAIL"),
    SLACK("SLACK"),
    PAGER_DUTY("PAGER_DUTY"),
    NA("NA");

    @JsonValue
    public final String value;

    private ActionType(String value) {
        this.value = value;
    }
}
