/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ActivateAzureSubscriptionRequest {
    @JsonProperty("email")
    public String email;

    public ActivateAzureSubscriptionRequest withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("expectExisting")
    public Boolean expectExisting;

    public ActivateAzureSubscriptionRequest withExpectExisting(Boolean expectExisting) {
        this.expectExisting = expectExisting;
        return this;
    }
    
    @JsonProperty("marketplaceToken")
    public String marketplaceToken;

    public ActivateAzureSubscriptionRequest withMarketplaceToken(String marketplaceToken) {
        this.marketplaceToken = marketplaceToken;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("modelName")
    public String modelName;

    public ActivateAzureSubscriptionRequest withModelName(String modelName) {
        this.modelName = modelName;
        return this;
    }
    
    @JsonProperty("orgName")
    public String orgName;

    public ActivateAzureSubscriptionRequest withOrgName(String orgName) {
        this.orgName = orgName;
        return this;
    }
    
    public ActivateAzureSubscriptionRequest(@JsonProperty("email") String email, @JsonProperty("marketplaceToken") String marketplaceToken, @JsonProperty("orgName") String orgName) {
        this.email = email;
        this.marketplaceToken = marketplaceToken;
        this.orgName = orgName;
  }
}
