/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AdminReportTimePeriod - A time period for the admin report.
 */
public enum AdminReportTimePeriod {
    WEEK("WEEK"),
    MONTH("MONTH"),
    YEAR("YEAR");

    @JsonValue
    public final String value;

    private AdminReportTimePeriod(String value) {
        this.value = value;
    }
}
