/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AsyncLogResponse - Response payload for LogAsync.
 */
public class AsyncLogResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;

    public AsyncLogResponse withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("modelId")
    public String modelId;

    public AsyncLogResponse withModelId(String modelId) {
        this.modelId = modelId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tags")
    public Segment tags;

    public AsyncLogResponse withTags(Segment tags) {
        this.tags = tags;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("uploadTimestamp")
    public Long uploadTimestamp;

    public AsyncLogResponse withUploadTimestamp(Long uploadTimestamp) {
        this.uploadTimestamp = uploadTimestamp;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("uploadUrl")
    public String uploadUrl;

    public AsyncLogResponse withUploadUrl(String uploadUrl) {
        this.uploadUrl = uploadUrl;
        return this;
    }
    
    public AsyncLogResponse(){}
}
