/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import ai.whylabs.WhyLabs.utils.DateTimeDeserializer;
import ai.whylabs.WhyLabs.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class AWSMarketplaceMetadata {
    @JsonProperty("awsMarketplaceCustomerId")
    public String awsMarketplaceCustomerId;

    public AWSMarketplaceMetadata withAwsMarketplaceCustomerId(String awsMarketplaceCustomerId) {
        this.awsMarketplaceCustomerId = awsMarketplaceCustomerId;
        return this;
    }
    
    @JsonProperty("awsMarketplaceProductCode")
    public String awsMarketplaceProductCode;

    public AWSMarketplaceMetadata withAwsMarketplaceProductCode(String awsMarketplaceProductCode) {
        this.awsMarketplaceProductCode = awsMarketplaceProductCode;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("createdBy")
    public String createdBy;

    public AWSMarketplaceMetadata withCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }
    
    @JsonProperty("dimension")
    public MarketplaceDimensions dimension;

    public AWSMarketplaceMetadata withDimension(MarketplaceDimensions dimension) {
        this.dimension = dimension;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("expirationTime")
    public OffsetDateTime expirationTime;

    public AWSMarketplaceMetadata withExpirationTime(OffsetDateTime expirationTime) {
        this.expirationTime = expirationTime;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("expirationUpdateTime")
    public OffsetDateTime expirationUpdateTime;

    public AWSMarketplaceMetadata withExpirationUpdateTime(OffsetDateTime expirationUpdateTime) {
        this.expirationUpdateTime = expirationUpdateTime;
        return this;
    }
    
    @JsonProperty("orgId")
    public String orgId;

    public AWSMarketplaceMetadata withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public AWSMarketplaceMetadata(@JsonProperty("awsMarketplaceCustomerId") String awsMarketplaceCustomerId, @JsonProperty("awsMarketplaceProductCode") String awsMarketplaceProductCode, @JsonProperty("dimension") MarketplaceDimensions dimension, @JsonProperty("expirationTime") OffsetDateTime expirationTime, @JsonProperty("expirationUpdateTime") OffsetDateTime expirationUpdateTime, @JsonProperty("orgId") String orgId) {
        this.awsMarketplaceCustomerId = awsMarketplaceCustomerId;
        this.awsMarketplaceProductCode = awsMarketplaceProductCode;
        this.dimension = dimension;
        this.expirationTime = expirationTime;
        this.expirationUpdateTime = expirationUpdateTime;
        this.orgId = orgId;
  }
}
