/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class AzureMarketplaceSubscriptionDetails {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("beneficiary")
    public AzureMarketplaceContactPayload beneficiary;

    public AzureMarketplaceSubscriptionDetails withBeneficiary(AzureMarketplaceContactPayload beneficiary) {
        this.beneficiary = beneficiary;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;

    public AzureMarketplaceSubscriptionDetails withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public AzureMarketplaceSubscriptionDetails withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("offerId")
    public String offerId;

    public AzureMarketplaceSubscriptionDetails withOfferId(String offerId) {
        this.offerId = offerId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("planId")
    public String planId;

    public AzureMarketplaceSubscriptionDetails withPlanId(String planId) {
        this.planId = planId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("publisherId")
    public String publisherId;

    public AzureMarketplaceSubscriptionDetails withPublisherId(String publisherId) {
        this.publisherId = publisherId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("purchaser")
    public AzureMarketplaceContactPayload purchaser;

    public AzureMarketplaceSubscriptionDetails withPurchaser(AzureMarketplaceContactPayload purchaser) {
        this.purchaser = purchaser;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("saasSubscriptionStatus")
    public String saasSubscriptionStatus;

    public AzureMarketplaceSubscriptionDetails withSaasSubscriptionStatus(String saasSubscriptionStatus) {
        this.saasSubscriptionStatus = saasSubscriptionStatus;
        return this;
    }
    
    public AzureMarketplaceSubscriptionDetails(){}
}
