/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class DeleteAnalyzerResult {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("creationTimestamp")
    public Long creationTimestamp;

    public DeleteAnalyzerResult withCreationTimestamp(Long creationTimestamp) {
        this.creationTimestamp = creationTimestamp;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("datasetId")
    public String datasetId;

    public DeleteAnalyzerResult withDatasetId(String datasetId) {
        this.datasetId = datasetId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("deleteGte")
    public Long deleteGte;

    public DeleteAnalyzerResult withDeleteGte(Long deleteGte) {
        this.deleteGte = deleteGte;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("deleteLt")
    public Long deleteLt;

    public DeleteAnalyzerResult withDeleteLt(Long deleteLt) {
        this.deleteLt = deleteLt;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public Integer id;

    public DeleteAnalyzerResult withId(Integer id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("orgId")
    public String orgId;

    public DeleteAnalyzerResult withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public DeletionStatus status;

    public DeleteAnalyzerResult withStatus(DeletionStatus status) {
        this.status = status;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("updatedTimestamp")
    public Long updatedTimestamp;

    public DeleteAnalyzerResult withUpdatedTimestamp(Long updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
        return this;
    }
    
    public DeleteAnalyzerResult(){}
}
