/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class DTOClustersAwsAttributesDTO {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("availability")
    public DTOClustersAwsAvailabilityDTO availability;

    public DTOClustersAwsAttributesDTO withAvailability(DTOClustersAwsAvailabilityDTO availability) {
        this.availability = availability;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ebsVolumeCount")
    public Integer ebsVolumeCount;

    public DTOClustersAwsAttributesDTO withEbsVolumeCount(Integer ebsVolumeCount) {
        this.ebsVolumeCount = ebsVolumeCount;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ebsVolumeSize")
    public Integer ebsVolumeSize;

    public DTOClustersAwsAttributesDTO withEbsVolumeSize(Integer ebsVolumeSize) {
        this.ebsVolumeSize = ebsVolumeSize;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ebsVolumeType")
    public DTOEbsVolumeTypeDTO ebsVolumeType;

    public DTOClustersAwsAttributesDTO withEbsVolumeType(DTOEbsVolumeTypeDTO ebsVolumeType) {
        this.ebsVolumeType = ebsVolumeType;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("firstOnDemand")
    public Integer firstOnDemand;

    public DTOClustersAwsAttributesDTO withFirstOnDemand(Integer firstOnDemand) {
        this.firstOnDemand = firstOnDemand;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("instanceProfileArn")
    public String instanceProfileArn;

    public DTOClustersAwsAttributesDTO withInstanceProfileArn(String instanceProfileArn) {
        this.instanceProfileArn = instanceProfileArn;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("spotBidPricePercent")
    public Integer spotBidPricePercent;

    public DTOClustersAwsAttributesDTO withSpotBidPricePercent(Integer spotBidPricePercent) {
        this.spotBidPricePercent = spotBidPricePercent;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("zoneId")
    public String zoneId;

    public DTOClustersAwsAttributesDTO withZoneId(String zoneId) {
        this.zoneId = zoneId;
        return this;
    }
    
    public DTOClustersAwsAttributesDTO(){}
}
