/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class DTOClustersDbfsStorageInfoDTO {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("destination")
    public String destination;

    public DTOClustersDbfsStorageInfoDTO withDestination(String destination) {
        this.destination = destination;
        return this;
    }
    
    public DTOClustersDbfsStorageInfoDTO(){}
}
