/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class DTOClustersAutoScaleDTO {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("maxWorkers")
    public Integer maxWorkers;

    public DTOClustersAutoScaleDTO withMaxWorkers(Integer maxWorkers) {
        this.maxWorkers = maxWorkers;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("minWorkers")
    public Integer minWorkers;

    public DTOClustersAutoScaleDTO withMinWorkers(Integer minWorkers) {
        this.minWorkers = minWorkers;
        return this;
    }
    
    public DTOClustersAutoScaleDTO(){}
}
