/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class DTOJobsJobEmailNotificationsDTO {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("noAlertForSkippedRuns")
    public Boolean noAlertForSkippedRuns;

    public DTOJobsJobEmailNotificationsDTO withNoAlertForSkippedRuns(Boolean noAlertForSkippedRuns) {
        this.noAlertForSkippedRuns = noAlertForSkippedRuns;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("onFailure")
    public java.util.Map<String, Object>[] onFailure;

    public DTOJobsJobEmailNotificationsDTO withOnFailure(java.util.Map<String, Object>[] onFailure) {
        this.onFailure = onFailure;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("onStart")
    public java.util.Map<String, Object>[] onStart;

    public DTOJobsJobEmailNotificationsDTO withOnStart(java.util.Map<String, Object>[] onStart) {
        this.onStart = onStart;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("onSuccess")
    public java.util.Map<String, Object>[] onSuccess;

    public DTOJobsJobEmailNotificationsDTO withOnSuccess(java.util.Map<String, Object>[] onSuccess) {
        this.onSuccess = onSuccess;
        return this;
    }
    
    public DTOJobsJobEmailNotificationsDTO(){}
}
