/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class DTOJobsSparkSubmitTaskDTO {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("parameters")
    public DTOJobsSparkSubmitTaskDTOParameters[] parameters;

    public DTOJobsSparkSubmitTaskDTO withParameters(DTOJobsSparkSubmitTaskDTOParameters[] parameters) {
        this.parameters = parameters;
        return this;
    }
    
    public DTOJobsSparkSubmitTaskDTO(){}
}
