/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum DTOJobsDataSecurityModeDTO {
    SINGLE_USER("SINGLE_USER"),
    USER_ISOLATION("USER_ISOLATION"),
    LEGACY_PASSTHROUGH("LEGACY_PASSTHROUGH"),
    LEGACY_TABLE_ACL("LEGACY_TABLE_ACL");

    @JsonValue
    public final String value;

    private DTOJobsDataSecurityModeDTO(String value) {
        this.value = value;
    }
}
