/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class DTOJobsJobEmailNotificationsDTO {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("noAlertForSkippedRuns")
    public Boolean noAlertForSkippedRuns;

    public DTOJobsJobEmailNotificationsDTO withNoAlertForSkippedRuns(Boolean noAlertForSkippedRuns) {
        this.noAlertForSkippedRuns = noAlertForSkippedRuns;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("onFailure")
    public OnFailure[] onFailure;

    public DTOJobsJobEmailNotificationsDTO withOnFailure(OnFailure[] onFailure) {
        this.onFailure = onFailure;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("onStart")
    public OnStart[] onStart;

    public DTOJobsJobEmailNotificationsDTO withOnStart(OnStart[] onStart) {
        this.onStart = onStart;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("onSuccess")
    public OnSuccess[] onSuccess;

    public DTOJobsJobEmailNotificationsDTO withOnSuccess(OnSuccess[] onSuccess) {
        this.onSuccess = onSuccess;
        return this;
    }
    
    public DTOJobsJobEmailNotificationsDTO(){}
}
