/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class DTOJobsNotebookTaskDTO {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("baseParameters")
    public java.util.Map<String, String> baseParameters;

    public DTOJobsNotebookTaskDTO withBaseParameters(java.util.Map<String, String> baseParameters) {
        this.baseParameters = baseParameters;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notebookPath")
    public String notebookPath;

    public DTOJobsNotebookTaskDTO withNotebookPath(String notebookPath) {
        this.notebookPath = notebookPath;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("revisionTimestamp")
    public Long revisionTimestamp;

    public DTOJobsNotebookTaskDTO withRevisionTimestamp(Long revisionTimestamp) {
        this.revisionTimestamp = revisionTimestamp;
        return this;
    }
    
    public DTOJobsNotebookTaskDTO(){}
}
