/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FeatureFlags - Feature flag state
 */
public class FeatureFlags {
    /**
     * The state of feature flags
     */
    @JsonProperty("flagValues")
    public java.util.Map<String, Boolean> flagValues;

    public FeatureFlags withFlagValues(java.util.Map<String, Boolean> flagValues) {
        this.flagValues = flagValues;
        return this;
    }
    
    public FeatureFlags(@JsonProperty("flagValues") java.util.Map<String, Boolean> flagValues) {
        this.flagValues = flagValues;
  }
}
