/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetAccountMembershipsResponse - Response for the GetAccountMemberships API
 */

public class GetAccountMembershipsResponse {
    /**
     * A list of memberships in the account
     */
    @JsonProperty("memberships")
    public OrganizationRoleMembers[] memberships;

    public GetAccountMembershipsResponse withMemberships(OrganizationRoleMembers[] memberships) {
        this.memberships = memberships;
        return this;
    }
    
    public GetAccountMembershipsResponse(@JsonProperty("memberships") OrganizationRoleMembers[] memberships) {
        this.memberships = memberships;
  }
}
