/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetMarketplaceMetadataResponse - Response for listing organization
 */

public class GetMarketplaceMetadataResponse {
    @JsonProperty("metadata")
    public AWSMarketplaceMetadata metadata;

    public GetMarketplaceMetadataResponse withMetadata(AWSMarketplaceMetadata metadata) {
        this.metadata = metadata;
        return this;
    }
    
    public GetMarketplaceMetadataResponse(@JsonProperty("metadata") AWSMarketplaceMetadata metadata) {
        this.metadata = metadata;
  }
}
