/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetSessionResponse - Response for getting sessions.
 */

public class GetSessionResponse {
    /**
     * Response for getting sessions.
     */
    @JsonProperty("session")
    public SessionMetadata session;

    public GetSessionResponse withSession(SessionMetadata session) {
        this.session = session;
        return this;
    }
    
    public GetSessionResponse(@JsonProperty("session") SessionMetadata session) {
        this.session = session;
  }
}
