/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListModelsResponse - Response for the ListModels API
 */
public class ListModelsResponse {
    /**
     * A list of all known model ids for an organization.
     */
    @JsonProperty("items")
    public ModelMetadataResponse[] items;

    public ListModelsResponse withItems(ModelMetadataResponse[] items) {
        this.items = items;
        return this;
    }
    
    public ListModelsResponse(@JsonProperty("items") ModelMetadataResponse[] items) {
        this.items = items;
  }
}
