/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * LogAsyncRequest - Request payload for LogAsync.
 */

public class LogAsyncRequest {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("datasetTimestamp")
    public Long datasetTimestamp;

    public LogAsyncRequest withDatasetTimestamp(Long datasetTimestamp) {
        this.datasetTimestamp = datasetTimestamp;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("segmentTags")
    public SegmentTag[] segmentTags;

    public LogAsyncRequest withSegmentTags(SegmentTag[] segmentTags) {
        this.segmentTags = segmentTags;
        return this;
    }
    
    public LogAsyncRequest(){}
}
