/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * LogReferenceResponse - Response payload for uploading reference profile.
 */

public class LogReferenceResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("alias")
    public String alias;

    public LogReferenceResponse withAlias(String alias) {
        this.alias = alias;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;

    public LogReferenceResponse withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("modelId")
    public String modelId;

    public LogReferenceResponse withModelId(String modelId) {
        this.modelId = modelId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("uploadTimestamp")
    public Long uploadTimestamp;

    public LogReferenceResponse withUploadTimestamp(Long uploadTimestamp) {
        this.uploadTimestamp = uploadTimestamp;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("uploadUrl")
    public String uploadUrl;

    public LogReferenceResponse withUploadUrl(String uploadUrl) {
        this.uploadUrl = uploadUrl;
        return this;
    }
    
    public LogReferenceResponse(){}
}
