/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * LogReferenceRequest - Request payload for LogReference.
 */
public class LogReferenceRequest {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("alias")
    public String alias;

    public LogReferenceRequest withAlias(String alias) {
        this.alias = alias;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("datasetTimestamp")
    public Long datasetTimestamp;

    public LogReferenceRequest withDatasetTimestamp(Long datasetTimestamp) {
        this.datasetTimestamp = datasetTimestamp;
        return this;
    }
    
    public LogReferenceRequest(){}
}
