/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum MarketplaceDimensions {
    FREE("FREE"),
    MODELS2("MODELS_2"),
    MODELS3("MODELS_3"),
    MODELS4("MODELS_4"),
    MODELS5("MODELS_5"),
    BY_QUANTITY("BY_QUANTITY"),
    ENTERPRISE("ENTERPRISE");

    @JsonValue
    public final String value;

    private MarketplaceDimensions(String value) {
        this.value = value;
    }
}
