/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Membership - Response for the get memberships
 */
public class Membership {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("default")
    public Boolean default_;

    public Membership withDefault(Boolean default_) {
        this.default_ = default_;
        return this;
    }
    
    @JsonProperty("email")
    public String email;

    public Membership withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonProperty("orgId")
    public String orgId;

    public Membership withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @JsonProperty("role")
    public Role role;

    public Membership withRole(Role role) {
        this.role = role;
        return this;
    }
    
    @JsonProperty("userId")
    public String userId;

    public Membership withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public Membership(@JsonProperty("email") String email, @JsonProperty("orgId") String orgId, @JsonProperty("role") Role role, @JsonProperty("userId") String userId) {
        this.email = email;
        this.orgId = orgId;
        this.role = role;
        this.userId = userId;
  }
}
