/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Member - Memberships by organization and role
 */

public class Member {
    @JsonProperty("email")
    public String email;

    public Member withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonProperty("userId")
    public String userId;

    public Member withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public Member(@JsonProperty("email") String email, @JsonProperty("userId") String userId) {
        this.email = email;
        this.userId = userId;
  }
}
