/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * MetricSchema - Schema for user-defined metrics
 */

public class MetricSchema {
    /**
     * Entity column to extract the metric from
     */
    @JsonProperty("column")
    public String column;

    public MetricSchema withColumn(String column) {
        this.column = column;
        return this;
    }
    
    /**
     * whylogs metric to extract. Note that other metrics may be available for this column as well, this is the one to be used by default. Should match the values of the SimpleColumnMetric enum within the monitor config schema.
     */
    @JsonProperty("defaultMetric")
    public String defaultMetric;

    public MetricSchema withDefaultMetric(String defaultMetric) {
        this.defaultMetric = defaultMetric;
        return this;
    }
    
    /**
     * User-friendly label for the metric. This should be a unique for the entity.
     */
    @JsonProperty("label")
    public String label;

    public MetricSchema withLabel(String label) {
        this.label = label;
        return this;
    }
    
    public MetricSchema(@JsonProperty("column") String column, @JsonProperty("defaultMetric") String defaultMetric, @JsonProperty("label") String label) {
        this.column = column;
        this.defaultMetric = defaultMetric;
        this.label = label;
  }
}
