/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ModelMetadataResponse - Response for the model metadata
 */

public class ModelMetadataResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("active")
    public Boolean active;

    public ModelMetadataResponse withActive(Boolean active) {
        this.active = active;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("creationTime")
    public Long creationTime;

    public ModelMetadataResponse withCreationTime(Long creationTime) {
        this.creationTime = creationTime;
        return this;
    }
    
    @JsonProperty("id")
    public String id;

    public ModelMetadataResponse withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("modelCategory")
    public String modelCategory;

    public ModelMetadataResponse withModelCategory(String modelCategory) {
        this.modelCategory = modelCategory;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("modelType")
    public String modelType;

    public ModelMetadataResponse withModelType(String modelType) {
        this.modelType = modelType;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public ModelMetadataResponse withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("orgId")
    public String orgId;

    public ModelMetadataResponse withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("timePeriod")
    public String timePeriod;

    public ModelMetadataResponse withTimePeriod(String timePeriod) {
        this.timePeriod = timePeriod;
        return this;
    }
    
    public ModelMetadataResponse(@JsonProperty("id") String id, @JsonProperty("name") String name) {
        this.id = id;
        this.name = name;
  }
}
