/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum NotificationSqsMessageCadence {
    HOURLY("HOURLY"),
    DAILY("DAILY"),
    WEEKLY("WEEKLY"),
    INDIVIDUAL("INDIVIDUAL");

    @JsonValue
    public final String value;

    private NotificationSqsMessageCadence(String value) {
        this.value = value;
    }
}
