/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * OrganizationMetadata - Metadata about an organization
 */

public class OrganizationMetadata {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("creationTime")
    public Long creationTime;

    public OrganizationMetadata withCreationTime(Long creationTime) {
        this.creationTime = creationTime;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("deleted")
    public Boolean deleted;

    public OrganizationMetadata withDeleted(Boolean deleted) {
        this.deleted = deleted;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("domain")
    public String domain;

    public OrganizationMetadata withDomain(String domain) {
        this.domain = domain;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("emailDomains")
    public String emailDomains;

    public OrganizationMetadata withEmailDomains(String emailDomains) {
        this.emailDomains = emailDomains;
        return this;
    }
    
    @JsonProperty("id")
    public String id;

    public OrganizationMetadata withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public OrganizationMetadata withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notificationEmailAddress")
    public String notificationEmailAddress;

    public OrganizationMetadata withNotificationEmailAddress(String notificationEmailAddress) {
        this.notificationEmailAddress = notificationEmailAddress;
        return this;
    }
    
    /**
     * Settings that control how and when notifications are delivered.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notificationSettings")
    public NotificationSettings notificationSettings;

    public OrganizationMetadata withNotificationSettings(NotificationSettings notificationSettings) {
        this.notificationSettings = notificationSettings;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("observatoryUrl")
    public String observatoryUrl;

    public OrganizationMetadata withObservatoryUrl(String observatoryUrl) {
        this.observatoryUrl = observatoryUrl;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pagerDutyKey")
    public String pagerDutyKey;

    public OrganizationMetadata withPagerDutyKey(String pagerDutyKey) {
        this.pagerDutyKey = pagerDutyKey;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("parentOrgId")
    public String parentOrgId;

    public OrganizationMetadata withParentOrgId(String parentOrgId) {
        this.parentOrgId = parentOrgId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("slackWebhook")
    public String slackWebhook;

    public OrganizationMetadata withSlackWebhook(String slackWebhook) {
        this.slackWebhook = slackWebhook;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("subscriptionId")
    public String subscriptionId;

    public OrganizationMetadata withSubscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("subscriptionTier")
    public SubscriptionTier subscriptionTier;

    public OrganizationMetadata withSubscriptionTier(SubscriptionTier subscriptionTier) {
        this.subscriptionTier = subscriptionTier;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("useCloudFront")
    public Boolean useCloudFront;

    public OrganizationMetadata withUseCloudFront(Boolean useCloudFront) {
        this.useCloudFront = useCloudFront;
        return this;
    }
    
    public OrganizationMetadata(@JsonProperty("id") String id) {
        this.id = id;
  }
}
