/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * OrganizationSummary - Summary about an organization
 */

public class OrganizationSummary {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("domain")
    public String domain;

    public OrganizationSummary withDomain(String domain) {
        this.domain = domain;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("emailDomains")
    public String emailDomains;

    public OrganizationSummary withEmailDomains(String emailDomains) {
        this.emailDomains = emailDomains;
        return this;
    }
    
    @JsonProperty("id")
    public String id;

    public OrganizationSummary withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public OrganizationSummary withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notificationEmailAddress")
    public String notificationEmailAddress;

    public OrganizationSummary withNotificationEmailAddress(String notificationEmailAddress) {
        this.notificationEmailAddress = notificationEmailAddress;
        return this;
    }
    
    /**
     * Settings that control how and when notifications are delivered.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notificationSettings")
    public NotificationSettings notificationSettings;

    public OrganizationSummary withNotificationSettings(NotificationSettings notificationSettings) {
        this.notificationSettings = notificationSettings;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("observatoryUrl")
    public String observatoryUrl;

    public OrganizationSummary withObservatoryUrl(String observatoryUrl) {
        this.observatoryUrl = observatoryUrl;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pagerDutyKey")
    public String pagerDutyKey;

    public OrganizationSummary withPagerDutyKey(String pagerDutyKey) {
        this.pagerDutyKey = pagerDutyKey;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("parentOrgId")
    public String parentOrgId;

    public OrganizationSummary withParentOrgId(String parentOrgId) {
        this.parentOrgId = parentOrgId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("slackWebhook")
    public String slackWebhook;

    public OrganizationSummary withSlackWebhook(String slackWebhook) {
        this.slackWebhook = slackWebhook;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("subscriptionTier")
    public SubscriptionTier subscriptionTier;

    public OrganizationSummary withSubscriptionTier(SubscriptionTier subscriptionTier) {
        this.subscriptionTier = subscriptionTier;
        return this;
    }
    
    public OrganizationSummary(@JsonProperty("id") String id) {
        this.id = id;
  }
}
