/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PagerDutyNotificationAction - Pager Duty payload for Notification Actions
 */

public class PagerDutyNotificationAction {
    @JsonProperty("pagerDutyKey")
    public String pagerDutyKey;

    public PagerDutyNotificationAction withPagerDutyKey(String pagerDutyKey) {
        this.pagerDutyKey = pagerDutyKey;
        return this;
    }
    
    public PagerDutyNotificationAction(@JsonProperty("pagerDutyKey") String pagerDutyKey) {
        this.pagerDutyKey = pagerDutyKey;
  }
}
