/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PatchAccountMembershipsRequest - Request for the PatchAccountMemberships API
 */

public class PatchAccountMembershipsRequest {
    /**
     * A list of userIds that should be members
     */
    @JsonProperty("userIdsToAdd")
    public String[] userIdsToAdd;

    public PatchAccountMembershipsRequest withUserIdsToAdd(String[] userIdsToAdd) {
        this.userIdsToAdd = userIdsToAdd;
        return this;
    }
    
    /**
     * A list of userIds that should not be members
     */
    @JsonProperty("userIdsToDelete")
    public String[] userIdsToDelete;

    public PatchAccountMembershipsRequest withUserIdsToDelete(String[] userIdsToDelete) {
        this.userIdsToDelete = userIdsToDelete;
        return this;
    }
    
    public PatchAccountMembershipsRequest(@JsonProperty("userIdsToAdd") String[] userIdsToAdd, @JsonProperty("userIdsToDelete") String[] userIdsToDelete) {
        this.userIdsToAdd = userIdsToAdd;
        this.userIdsToDelete = userIdsToDelete;
  }
}
