/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ProfileTracesResponse - Response for listing profile traces
 */

public class ProfileTracesResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("nextOffset")
    public Integer nextOffset;

    public ProfileTracesResponse withNextOffset(Integer nextOffset) {
        this.nextOffset = nextOffset;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("traces")
    public ProfileTrace[] traces;

    public ProfileTracesResponse withTraces(ProfileTrace[] traces) {
        this.traces = traces;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("truncated")
    public Boolean truncated;

    public ProfileTracesResponse withTruncated(Boolean truncated) {
        this.truncated = truncated;
        return this;
    }
    
    public ProfileTracesResponse(){}
}
