/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ProvisionNewUserRequest {
    @JsonProperty("email")
    public String email;

    public ProvisionNewUserRequest withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("expectExisting")
    public Boolean expectExisting;

    public ProvisionNewUserRequest withExpectExisting(Boolean expectExisting) {
        this.expectExisting = expectExisting;
        return this;
    }
    
    @JsonProperty("modelName")
    public String modelName;

    public ProvisionNewUserRequest withModelName(String modelName) {
        this.modelName = modelName;
        return this;
    }
    
    @JsonProperty("orgName")
    public String orgName;

    public ProvisionNewUserRequest withOrgName(String orgName) {
        this.orgName = orgName;
        return this;
    }
    
    @JsonProperty("subscriptionTier")
    public SubscriptionTier subscriptionTier;

    public ProvisionNewUserRequest withSubscriptionTier(SubscriptionTier subscriptionTier) {
        this.subscriptionTier = subscriptionTier;
        return this;
    }
    
    public ProvisionNewUserRequest(@JsonProperty("email") String email, @JsonProperty("modelName") String modelName, @JsonProperty("orgName") String orgName, @JsonProperty("subscriptionTier") SubscriptionTier subscriptionTier) {
        this.email = email;
        this.modelName = modelName;
        this.orgName = orgName;
        this.subscriptionTier = subscriptionTier;
  }
}
