/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class ProvisionNewUserResponse {
    @JsonProperty("modelId")
    public String modelId;

    public ProvisionNewUserResponse withModelId(String modelId) {
        this.modelId = modelId;
        return this;
    }
    
    @JsonProperty("orgId")
    public String orgId;

    public ProvisionNewUserResponse withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @JsonProperty("userId")
    public String userId;

    public ProvisionNewUserResponse withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public ProvisionNewUserResponse(@JsonProperty("modelId") String modelId, @JsonProperty("orgId") String orgId, @JsonProperty("userId") String userId) {
        this.modelId = modelId;
        this.orgId = orgId;
        this.userId = userId;
  }
}
