/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class ProvisionDatabricksConnectionResponse {
    @JsonProperty("orgId")
    public String orgId;

    public ProvisionDatabricksConnectionResponse withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @JsonProperty("userId")
    public String userId;

    public ProvisionDatabricksConnectionResponse withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    @JsonProperty("workspaceId")
    public String workspaceId;

    public ProvisionDatabricksConnectionResponse withWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }
    
    public ProvisionDatabricksConnectionResponse(@JsonProperty("orgId") String orgId, @JsonProperty("userId") String userId, @JsonProperty("workspaceId") String workspaceId) {
        this.orgId = orgId;
        this.userId = userId;
        this.workspaceId = workspaceId;
  }
}
