/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ProvisionNewMarketplaceUserRequest {
    @JsonProperty("customerIdToken")
    public String customerIdToken;

    public ProvisionNewMarketplaceUserRequest withCustomerIdToken(String customerIdToken) {
        this.customerIdToken = customerIdToken;
        return this;
    }
    
    @JsonProperty("email")
    public String email;

    public ProvisionNewMarketplaceUserRequest withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("expectExisting")
    public Boolean expectExisting;

    public ProvisionNewMarketplaceUserRequest withExpectExisting(Boolean expectExisting) {
        this.expectExisting = expectExisting;
        return this;
    }
    
    @JsonProperty("modelName")
    public String modelName;

    public ProvisionNewMarketplaceUserRequest withModelName(String modelName) {
        this.modelName = modelName;
        return this;
    }
    
    @JsonProperty("orgName")
    public String orgName;

    public ProvisionNewMarketplaceUserRequest withOrgName(String orgName) {
        this.orgName = orgName;
        return this;
    }
    
    public ProvisionNewMarketplaceUserRequest(@JsonProperty("customerIdToken") String customerIdToken, @JsonProperty("email") String email, @JsonProperty("modelName") String modelName, @JsonProperty("orgName") String orgName) {
        this.customerIdToken = customerIdToken;
        this.email = email;
        this.modelName = modelName;
        this.orgName = orgName;
  }
}
