/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RegisterDatabricksConnectionResponse - RegisterDatabricksConnection default response
 */
public class RegisterDatabricksConnectionResponse {
    @JsonProperty("id")
    public String id;

    public RegisterDatabricksConnectionResponse withId(String id) {
        this.id = id;
        return this;
    }
    
    public RegisterDatabricksConnectionResponse(@JsonProperty("id") String id) {
        this.id = id;
  }
}
