/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class RunJobRequest {
    /**
     * The id of the job to run in the connected Databricks workspace.
     */
    @JsonProperty("jobId")
    public Long jobId;

    public RunJobRequest withJobId(Long jobId) {
        this.jobId = jobId;
        return this;
    }
    
    /**
     * Look up a connection by the org that is connected to.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("orgId")
    public String orgId;

    public RunJobRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    /**
     * Look up a connection by the workspace that it originates from.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("workspaceId")
    public String workspaceId;

    public RunJobRequest withWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId;
        return this;
    }
    
    public RunJobRequest(@JsonProperty("jobId") Long jobId) {
        this.jobId = jobId;
  }
}
