/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RunJobResponse - RunJob default response
 */
public class RunJobResponse {
    @JsonProperty("runId")
    public Long runId;

    public RunJobResponse withRunId(Long runId) {
        this.runId = runId;
        return this;
    }
    
    public RunJobResponse(@JsonProperty("runId") Long runId) {
        this.runId = runId;
  }
}
