/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SearchIndexType {
    MODELS("MODELS"),
    ACTIONS("ACTIONS"),
    ENTITY_SCHEMA("ENTITY_SCHEMA"),
    MONITOR_CONFIG("MONITOR_CONFIG");

    @JsonValue
    public final String value;

    private SearchIndexType(String value) {
        this.value = value;
    }
}
