/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class Segment {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tags")
    public SegmentTag[] tags;

    public Segment withTags(SegmentTag[] tags) {
        this.tags = tags;
        return this;
    }
    
    public Segment(){}
}
