/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SegmentTag - A key value tag
 */

public class SegmentTag {
    @JsonProperty("key")
    public String key;

    public SegmentTag withKey(String key) {
        this.key = key;
        return this;
    }
    
    @JsonProperty("value")
    public String value;

    public SegmentTag withValue(String value) {
        this.value = value;
        return this;
    }
    
    public SegmentTag(@JsonProperty("key") String key, @JsonProperty("value") String value) {
        this.key = key;
        this.value = value;
  }
}
