/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SetDefaultMembershipRequest {
    @JsonProperty("orgId")
    public String orgId;

    public SetDefaultMembershipRequest withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    @JsonProperty("userId")
    public String userId;

    public SetDefaultMembershipRequest withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public SetDefaultMembershipRequest(@JsonProperty("orgId") String orgId, @JsonProperty("userId") String userId) {
        this.orgId = orgId;
        this.userId = userId;
  }
}
