/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * TimePeriod - The [TimePeriod] for data aggregation/alerting for a model
 */
public enum TimePeriod {
    P1_M("P1M"),
    P1_W("P1W"),
    P1_D("P1D"),
    PT1_H("PT1H");

    @JsonValue
    public final String value;

    private TimePeriod(String value) {
        this.value = value;
    }
}
