/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * TransactionStatusResponse - Response payload for Transaction status.
 */

public class TransactionStatusResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("files")
    public String[] files;

    public TransactionStatusResponse withFiles(String[] files) {
        this.files = files;
        return this;
    }
    
    public TransactionStatusResponse(){}
}
