/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class UpdateConnectionChanges {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("connected")
    public Boolean connected;

    public UpdateConnectionChanges withConnected(Boolean connected) {
        this.connected = connected;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("demo")
    public Boolean demo;

    public UpdateConnectionChanges withDemo(Boolean demo) {
        this.demo = demo;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("orgId")
    public String orgId;

    public UpdateConnectionChanges withOrgId(String orgId) {
        this.orgId = orgId;
        return this;
    }
    
    public UpdateConnectionChanges(){}
}
