/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * UpdateAccountUserRequest - Request to update a user in an account
 */

public class UpdateAccountUserRequest {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("active")
    public Boolean active;

    public UpdateAccountUserRequest withActive(Boolean active) {
        this.active = active;
        return this;
    }
    
    /**
     * The external id the user is known by in the provisioner
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("externalId")
    public String externalId;

    public UpdateAccountUserRequest withExternalId(String externalId) {
        this.externalId = externalId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("userSchema")
    public String userSchema;

    public UpdateAccountUserRequest withUserSchema(String userSchema) {
        this.userSchema = userSchema;
        return this;
    }
    
    public UpdateAccountUserRequest(){}
}
