/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * User - User metadata
 */
public class User {
    /**
     * The user's email address.
     */
    @JsonProperty("email")
    public String email;

    public User withEmail(String email) {
        this.email = email;
        return this;
    }
    
    /**
     * The user's JSON serialized preferences. Schema defined in Dashbird.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("preferences")
    public String preferences;

    public User withPreferences(String preferences) {
        this.preferences = preferences;
        return this;
    }
    
    /**
     * The id of the user.
     */
    @JsonProperty("userId")
    public String userId;

    public User withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public User(@JsonProperty("email") String email, @JsonProperty("userId") String userId) {
        this.email = email;
        this.userId = userId;
  }
}
