/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * UserApiKeyResponse - An key metadata object but no secret values
 */
public class UserApiKeyResponse {
    /**
     * Response when creating an API key successfully
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("key")
    public UserApiKey key;

    public UserApiKeyResponse withKey(UserApiKey key) {
        this.key = key;
        return this;
    }
    
    public UserApiKeyResponse(){}
}
