/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs.models.shared;



/**
 * Void - ClaimGuestSession default response
 */
public class Void {
    public Void(){}
}
