/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package ai.whylabs.WhyLabs;

import ai.whylabs.WhyLabs.utils.HTTPClient;
import ai.whylabs.WhyLabs.models.shared.Security;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	public Security security;
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "0.1";
	public String sdkVersion = "2.1.1";
	public String genVersion = "2.228.1";
	public String userAgent = "speakeasy-sdk/java 2.1.1 2.228.1 0.1 ai.whylabs.WhyLabs";
	
	
}